name: unittest

on:
  pull_request:
    paths:
      - server/**
  push:
    branches: [main]
    paths:
      - server/**

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        cd server
        python -m pip install -r requirements.txt
    - name: Run all unit tests
      run: |
        cd server
        python -m unittest discover -v
